accounts/urls.py
from django.urls import  path
from accounts import  views

app_name = 'accounts'
urlpatterns = [
	path('signup/', views.SignUp.as_view(), name='signup'),
    ]

booker/urls.py
from django.urls import  path
from booker import  views
from django.contrib.auth.decorators import login_required

app_name = 'booker'
urlpatterns = [
	path('', views.index,
		name='index'),
	path('<int:pk>/about/requestedbook', 
			views.RequestedBookView.as_view(),
			name='request_detail'),
	path('<int:pk>/about/offeredbook', 
			views.OfferedBookView.as_view(),
			name='offer_detail'),
	path('request/book', login_required(views.BookRequestView.as_view()),
		name='request_book'),
	path('request/list', login_required(views.RequestListView.as_view()),
		name='request_list'),
	path('offer/list', login_required(views.OfferListView.as_view()),
		name='offer_list'),
	path('request/success', views.request_success,
		name='request_success'),
	path('offer/book', login_required(views.BookOfferView.as_view()),
		name='offer_book'),
	path('offer/success', views.offer_success,
		name='offer_success'),
	path('booker/api', views.BookerApiView.as_view(),
		name='booker_api'),
	path('bookrequest/api', login_required(views.BookRequestApiView.as_view()),
		name='bookrequest_api'),
	path('<int:pk>/delete/request', views.delete_requested_book, 
		name='delete_requested_book'),
	path('<int:pk>/delete/offer', views.delete_offered_book,
		name= 'delete_offered_book'),
    ]

bookmall/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('booker.urls', namespace='booker')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),
]

accounts/models.py
from django.db import models

# Create your models here.

booker/models.py
from django.db import models
from django.conf import settings



offer_type = (
	('Free', 'Free'),
	('Negotiable', 'Negotiable'),
	)

class Booker(models.Model):
	id = models.IntegerField(primary_key=True, editable=False)
	bookman = models.ForeignKey(to=settings.AUTH_USER_MODEL,
						 on_delete=models.SET_NULL, null=True, default=1)
	title = models.CharField(max_length=200, blank=False, null=False)
	author = models.CharField(max_length=100, blank=False, null=False)
	price = models.CharField(choices=offer_type, max_length=100, default='Free')
	location = models.CharField(max_length=100, blank=False, null=False, 
		default='Nigeria')
	def __str__(self):
		return str(self.title) + ' by ' + str(self.author)


class BookRequest(models.Model):
	id = models.IntegerField(primary_key=True, editable=False)
	bookman = models.ForeignKey(to=settings.AUTH_USER_MODEL,
		on_delete=models.SET_NULL, null=True, default=1)
	title = models.CharField(max_length=200, null=False, blank=False)
	author = models.CharField(max_length=100, null= False, blank=False)
	location = models.CharField(max_length=100, null=False, blank=False)
	def __str__(self):
		return str(self.title) + ' by ' + str(self.author)

		

booker/forms.py
from django.forms import ModelForm, PasswordInput
from booker.models import BookRequest, Booker 



class BookRequestForm(ModelForm):
	class Meta:
		model = BookRequest 
		exclude = ['bookman']


class BookOfferForm(ModelForm):
	class Meta:
		model = Booker
		exclude = ['bookman']

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

booker/views.py
from django.shortcuts import render, render_to_response
from django.views import generic 
from booker.models import Booker, BookRequest
from booker.forms import BookRequestForm, BookOfferForm
from django.conf import settings
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from rest_framework.views import APIView
from rest_framework.response import Response 
from booker.serializers import BookerSerializer, BookRequestSerializer
from rest_framework import status
from django.contrib.auth.models import User 
from django.http import HttpResponseRedirect
from django.db.models import Q 


'''class Homepage(generic.ListView):
	model = Booker 
	requests = list(BookRequest.objects.all())
	context = {'requests':requests}
	def  get_queryset(self):
		return Booker.objects.all()'''

class RequestedBookView(generic.DetailView):
	model = BookRequest 

class OfferedBookView(generic.DetailView):
	model = Booker
	
class OfferListView(generic.ListView):
	model = Booker
	template_name = 'booker/offer_list.html'

	def get_queryset(self):
		return Booker.objects.filter(
			bookman=self.request.user
			)

class RequestListView(generic.ListView):
	model = BookRequest
	template_name = 'booker/request_list.html'
	def get_queryset(self, *args, **kwargs):
		return BookRequest.objects.filter(
			bookman=self.request.user
			).order_by('id')


class BookRequestView(generic.CreateView):
	form_class = BookRequestForm
	template_name = 'booker/request_book.html'
	success_url = reverse_lazy('booker:request_success')

	def form_valid(self, form_class):
		print(self.request.user)
		book_requested = form_class.save(commit=False)
		book_requested.bookman = User.objects.get(username=self.request.user)
		book_requested.save()
		return HttpResponseRedirect(self.success_url)

class BookOfferView(generic.CreateView):
	form_class = BookOfferForm
	template_name = 'booker/offer_book.html'
	success_url = reverse_lazy('booker:offer_success')

	def form_valid(self, form_class):
		print(self.request.user)
		book_requested = form_class.save(commit=False)
		book_requested.bookman = User.objects.get(username=self.request.user)
		book_requested.save()
		return HttpResponseRedirect(self.success_url)


def index(request):
	book_requests = list(BookRequest.objects.all())[::-1]
	book_offers = list(Booker.objects.all())[::-1]
	query = request.GET.get('offerbook', '')
	requestquery = request.GET.get('requestbook', '')
	if query:
		qset = (
			Q(title__contains=query) |
			Q(author__icontains=query) |
			Q(location__icontains=query) |
			Q(price__icontains=query)
			)
		results = Booker.objects.filter(qset).distinct()
	elif requestquery:
		qset = (
			Q(title__contains=requestquery) |
			Q(author__icontains=requestquery) |
			Q(location__icontains=requestquery) 
			)
		results = BookRequest.objects.filter(qset).distinct()
	else:
		results = []


	return render(request, 
		'booker/booker_list.html',
		 {'book_requests':book_requests, 'book_offers':book_offers,
		 'results':results, 'query':query, 'requestquery':requestquery,})
	

@login_required
def request_success(request):
	return render(request, 'booker/request_success.html', {})

@login_required
def offer_success(request):
	return render(request, 'booker/offer_success.html', {})

class BookerApiView(APIView):
	def get(self, response):
		booker = Booker.objects.all()
		serializer = BookerSerializer(booker, many=True)
		return Response(serializer.data)

	def post(self, response):
		serializer = BookerSerializer(data=response.data, many=True)
		if serializer.is_valid():
			serializer.save()
			return Response(serializer.data, 
				status=status.HTTP_201_CREATED)
		return Response(serializer.errors, 
			status=status.HTTP_400_BAD_REQUEST)

class BookRequestApiView(APIView):
	def get(self, response):
		bookrequest = BookRequest.objects.all()
		serializer = BookRequestSerializer(bookrequest, many=True)
		return Response(serializer.data)

	def post(self, response):
		serializer = BookRequestSerializer(data=response.data, many=True)
		if serializer.is_valid():
			serializer.save()
			return Response(serializer.data,
				status=status.HTTP_201_CREATED)
		return Response(serializer.errors, 
			status=status.HTTP_400_BAD_REQUEST)


def delete_offered_book(request, pk):
	book = Booker.objects.get(id=pk)
	book.delete()

	book_list = Booker.objects.filter(
			bookman=request.user
			)
	return render(request, 
		'booker/offered_book_deleted.html',
			 {'books':book_list})

def delete_requested_book(request, pk):
	book = BookRequest.objects.get(id=pk)
	book.delete()
	book_list = BookRequest.objects.filter(
			bookman=request.user
			)
	return render(request, 
		'booker/requested_book_deleted.html',
			 {'books':book_list})


def search_offered_books(request):
	query = request.GET.get('book', '')
	if query:
		qset = (
			Booker(title__icontains=query) |
			Booker(author__icontains=query) |
			Booker(location__icontains=query) |
			Booker(price__icontains=query)
			)
		results = Booker.objects.filter(qset).distinct()
	else:
		request = []

	return render_to_response('booker/search_offered.html',
		{'results': results, 'query': query})

booker/templates/booker/booker_detail.html
{% extends 'base.html' %}

{% block title %}
Bookmall
{% endblock %}


{% block body %}

 	<h4> Book title: {{ booker.title }}  </h4>	
 	<h4>Author: {{ booker.author }}  </h4>
 	<h4>Location: {{ booker.location }}  </h4>
<br>
<p>Posted by {{ booker.bookman }} </p>
 {% if booker.bookman == request.user %}
 <p><a href="{% url 'booker:delete_offered_book' pk=booker.id %}"> Delete book </a> </p>
 <br>
{% endif %}
{% endblock %}

booker/templates/booker/booker_list.html
{% extends 'base.html' %}
{% block title %}
Bookmall

{% endblock %}

{% block body %}

<div class="container">
	<div class="row">
		<div class="col-sm-6">
			<p>Search here for books currently on request</p>
			<span>
				<form method="GET" action=".">
					{% csrf_token %}
					<input type="text" name="requestbook" placeholder="enter book details" value="{{ requestbook|escape }}">
					
				<input type="submit" name="request" value="Search">
				</form>
			</span>
			<br>
			<br>
		</div>
		<div class="col-sm-6">
			<p>Search here for books being offered</p>
			<span>
				<form method="GET" action=".">
					{% csrf_token %}
					<input type="text" name="offerbook" placeholder="enter book details" value="{{ query|escape }}">
					
				<input type="submit" name="offer" value="Search">
				</form>
			</span>
			<br>
			<br>
		</div>

	</div>
	<div class="row">
		<div class="col-sm-6">
			{% if query %}
			<h2>Results for "{{ query|escape }}": </h2>
			{% if results %}
			<ul>
				{% for book in results %}
			 	<li><a href="{% url 'booker:offer_detail' pk=book.id %}" > {{ book|escape }} </a> </li>
				{% endfor %}
			</ul>
			{% else %}
			<p>No books found</p>
			{% endif %}
			{% endif %}
			{% if requestquery %}
				<h2>Results for "{{ requestquery|escape }}": </h2>
				{% if results %}
				<ul>
					{% for book in results %}
				<li><a href="{% url 'booker:request_detail' pk=book.id %}" > {{ book|escape }} </a> </li>
					{% endfor %}
				</ul>
			{% endif %}
			{% endif %}
		</div>
	</div>
	<br>
	<br>
</div>

<div class="container">
	<div class="row">
		<div class="col-sm-6">
				The list of books on request:
				<ul>
					{% for book in book_requests %}
				 	<li><a href="{% url 'booker:request_detail' pk=book.id %}" > {{ book }} </a> </li>
				 	{% endfor %}	
				</ul>

		</div>
		<div class="col-sm-6">
				The list of books currently offered:
				<ul>
					{% for book in book_offers %}
				 	<li><a href="{% url 'booker:offer_detail' pk=book.id %}" > {{ book }} </a> </li>
				 	{% endfor %}	
				</ul>
		</div>
</div>
 
{% endblock %}

booker/templates/booker/bookrequest_detail.html
{% extends 'base.html' %}

{% block title %}
Bookmall
{% endblock %}


{% block body %}

 	<h3> {{ bookrequest.title }}  </h3>
 	<h3> {{ bookrequest.author }}  </h3>
 	<h3> {{ bookrequest.location }}  </h3>

<p>Posted by {{ bookrequest.bookman }} </p>
{% if bookrequest.bookman == request.user %}
 <p><a href="{% url 'booker:delete_requested_book' pk=bookrequest.id %}"> Delete book </a> </p>
 <br>
{% endif %} 
{% endblock %}

booker/templates/booker/offer_book.html
{% extends 'base.html' %}

{% block title %}Offer Book{% endblock %}

{% block body %}
<form method="post">
	{% csrf_token %}
 {{ form.as_p }}
 <button type="submit">Submit Request</button>
</form>
{% endblock %}

booker/templates/booker/offer_list.html
{% extends 'base.html' %}

{% block title %}Request List{% endblock %}

{% block body %}
 
  {% if booker_list %}
   <h3>Your Offer List</h3>
   <br>
   <br>
   <ol>
 {% for book in booker_list %}
 <li><a href="{% url 'booker:offer_detail' pk=book.id %}" /> {{ book }}</li>

 <br>
 {% endfor %}
</ol>
 <br>
 <br>
 <a href="{% url 'booker:offer_book' %}">Offer another Book</a>
 {% else %}
 <h3>You have no book offer yet</h3>
 <p>You have no requests yet</p>
 <br>
 <br>
 <p>Will you like to Offer a Book now?</p>
 <a href="{% url 'booker:offer_book' %}">Offer a Book</a>
 {% endif %}

{% endblock %}

booker/templates/booker/offer_success.html
{% extends 'base.html' %}

{% block title %}Offer Success{% endblock %}

{% block body %}
Thank you for offering a book today... You're a Hero.

<br>

<p>have more books to offer?</p>

 <a href="{% url 'booker:offer_book' %}">Offer another book today</a>
{% endblock %}

booker/templates/booker/offered_book_deleted.html
{% extends 'base.html' %}

{% block title %}Delete Success{% endblock %}

{% block body %}
This book has been deleted successfully.

<h3>Your Offer List</h3>
   <br>
   <br>
   <ol>
 {% for book in books %}
 <li> {{ book }}</li>
 <p><a href="{% url 'booker:delete_offered_book' pk=book.id %}"> Delete book </a> </p>
 <br>
 {% endfor %}

 <a href="{% url 'booker:offer_book' %}">Offer another book </a>
{% endblock %}

booker/templates/booker/request_book.html
{% extends 'base.html' %}

{% block title %}Request Book{% endblock %}

{% block body %}
<form method="post">
	{% csrf_token %}
 {{ form.as_p }}
 <button type="submit">Submit Request</button>
</form>
{% endblock %}

booker/templates/booker/request_list.html
{% extends 'base.html' %}

{% block title %}Request List{% endblock %}

{% block body %}
 
  {% if bookrequest_list %}
   <h3>Your Book Request List</h3>
   <br>
   <br>
    <ol>
 {% for book in bookrequest_list.reverse %}

<li><a href="{% url 'booker:request_detail' pk=book.id %}" /> {{ book }}</li>


 {% endfor %}
  </ol>
<br>
 <br>
 <a href="{% url 'booker:request_book' %}">Place Another Book Request</a>
 {% else %}
 <p>You have no requests yet</p>
 <p>Will you like to place a request now?</p>
 <a href="{% url 'booker:request_book' %}">Place a Request</a>
 {% endif %}
 

{% endblock %}

booker/templates/booker/request_success.html
{% extends 'base.html' %}

{% block title %}Request Success{% endblock %}

{% block body %}
Thank you for requesting today... we will get in touch with you shortly.


 <a href="{% url 'booker:request_book' %}">Place another Request</a>
{% endblock %}

booker/templates/booker/requested_book_deleted.html
{% extends 'base.html' %}

{% block title %}Delete Success{% endblock %}

{% block body %}
This book has been deleted successfully.

<h3>Your Request List</h3>
   <br>
   <br>
   <ol>
 {% for book in books %}
 <li> {{ book }}</li>
 <p><a href="{% url 'booker:delete_requested_book' pk=book.id %}"> Delete book </a> </p>
 <br>
 {% endfor %}

 <a href="{% url 'booker:request_book' %}">Request another book </a>
{% endblock %}

booker/templates/booker/sign_up.html
{% extends 'base.html' %}


{% block title %}
Sign up 
{% endblock %}

{% block body %}
<h1>Sign up today to Start Requesting for books</h1>
<form method="post" action="{% url 'booker:signup_success' %}">
	{% csrf_token %}
	{{ form }}
	<input type="submit" value='submit' name="Sign up">
</form>
{% endblock %}

booker/templates/booker/sign_up_success.html
{% extends 'base.html' %}


{% block title %}
Sign up 
{% endblock %}

{% block body %}
<h3>Thanks for Signing up {{ name }} , check your email address for further details.</h3>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>
		{% block title %}
		{% endblock %}
	</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css"/>
	<link rel="stylesheet" type="text/css" 
	href="{% static 'booker/css/style.css' %}">
	<style type="text/css">
		.navbar-brand{
			display: inline-flex !important;
			list-style: none !important;
		}

		ul.topnav {
  list-style-type: none;
  margin: 0;
  padding: 0;
  overflow: hidden;
  background-color: grey;
}

ul.topnav li {float: left;}

ul.topnav li a {
  display: block;
  color: white;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}

ul.topnav li a:hover:not(.active) {background-color: #111;}

ul.topnav li a.active {background-color: blue;}

ul.topnav li.right {float: right;}

@media screen and (max-width: 600px) {
  ul.topnav li.right, 
  ul.topnav li {float: none;}
}
	</style>
</head>
<body>

	<div class="container">
		
			<ul class="topnav" >
				<li><a class="nav-link"href='{% url "booker:index" %}'>Home</a>
					
				</li>
				{% if request.user.is_authenticated %}
				<li>
					<a class="nav-link" href="{% url 'booker:request_list' %}">Your Request List</a>
				</li>
				<li>
					<a class="nav-link" href="{% url 'booker:offer_list' %}">Your Offer List</a> 
				</li>
				<li >
				
					<a class="nav-link" href="{% url 'logout' %}">Logout</a>
			
				</li>
				{% else %}
				<li >
					<a class="nav-link" href="{% url 'login' %}">Login</a>
				</li>
				<li >
					<a class="nav-link" href="{% url 'accounts:signup' %}">Sign up to Request</a>
				</li>
				
				{% endif %}
			</ul>
		

	</div>
	<div class="container" style="float: right; padding-top: 50px;">
				{% block body %}

		{% endblock %}
	</div>
</body>
</html>

templates/signup.html
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block body %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}